import Head from "next/head";
import Sidenavbar from "../navigation";

function Pagetemplate() {
  return (
    <div>
      <Head>
        <title className="text-[700]">Arizonna</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-[20%_80%]">
        <Sidenavbar />
        <div></div>
      </div>
    </div>
  );
}

export default Pagetemplate;
